INSERT INTO cidades (nome,  id_estado) VALUES('Aracajú',26);
INSERT INTO cidades (nome,  id_estado) VALUES('Belém',14);
INSERT INTO cidades (nome,  id_estado) VALUES('Belo Horizonte',13);
INSERT INTO cidades (nome,  id_estado) VALUES('Boa Vista',23);
INSERT INTO cidades (nome,  id_estado) VALUES('Brasília',7);
INSERT INTO cidades (nome,  id_estado) VALUES('Campo Grande',12);
INSERT INTO cidades (nome,  id_estado) VALUES('Cuiabá',11);
INSERT INTO cidades (nome,  id_estado) VALUES('Curitiba',16);
INSERT INTO cidades (nome,  id_estado) VALUES('Florianópolis',24);
INSERT INTO cidades (nome,  id_estado) VALUES('Fortaleza',6);
INSERT INTO cidades (nome,  id_estado) VALUES('Goiânia',9);
INSERT INTO cidades (nome,  id_estado) VALUES('João Pessoa',15);
INSERT INTO cidades (nome,  id_estado) VALUES('Macap ',3);
INSERT INTO cidades (nome,  id_estado) VALUES('Maceió',2);
INSERT INTO cidades (nome,  id_estado) VALUES('Manaus',4);
INSERT INTO cidades (nome,  id_estado) VALUES('Natal',20);
INSERT INTO cidades (nome,  id_estado) VALUES('Palmas',27);
INSERT INTO cidades (nome,  id_estado) VALUES('Porto Alegre',21);
INSERT INTO cidades (nome,  id_estado) VALUES('Porto Velho',22);
INSERT INTO cidades (nome,  id_estado) VALUES('Recife',17);
INSERT INTO cidades (nome,  id_estado) VALUES('Rio Branco',1);
INSERT INTO cidades (nome,  id_estado) VALUES('Rio de Janeiro',19);
INSERT INTO cidades (nome,  id_estado) VALUES('Salvador',5);
INSERT INTO cidades (nome,  id_estado) VALUES('São Luis',10);
INSERT INTO cidades (nome,  id_estado) VALUES('São Paulo',25);
INSERT INTO cidades (nome,  id_estado) VALUES('Teresina',18);
INSERT INTO cidades (nome,  id_estado) VALUES('Vitória',8)